### ISSUE TITLE
Cannot install on fresh install of Endeavour

### ISSUE THREAD

**Issue by CillyCil** [EndeavourOS-Community-Editions/leftwm#2]
Whenever I attempt to install using install_packages.sh I get these error:

error: target not found: archlinux-logout-git
warning: autorandr-1.12.1-2 is up to date -- skipping
 there is nothing to do
warning: dmenu-5.1-1 is up to date -- skipping
 there is nothing to do
warning: feh-3.8-2 is up to date -- skipping
 there is nothing to do
error: target not found: leftwm-dev-git
error: target not found: leftwm-theme-git

**Comment by erikdubois** [comment]
that is normal - check out my videos
https://www.youtube.com/playlist?list=PLlloYVGq5pS6xLLQQ0VhJ15rFgtL3OtIZ
we have activated the ArcoLinux repos
in the future EndeavourOS will have to host the packages they are missing
@killajoe

**Comment by killajoe** [comment]
or you would need to build the packages from AUR ..

**Comment by killajoe** [comment]
@erikdubois will the AUR PKGBUILD for arcolinux-logout-git get changed to archlinux-logout-git ? 
I see source is now renamed?
https://github.com/arcolinux/archlinux-logout
I know you are not maintaining the AUR build i could hint the maintainer there ?

**Comment by erikdubois** [comment]
you can hint the maintainer of the AUR package
I will never make a PKGBUILD again on the AUR
I have to much self respect to do so and I have never liked bullies.

**Comment by CillyCil** [comment]
Thanks for the help. I'm used to Debian and I'm just starting Arch so I'm just learning as I go.

**Comment by killajoe** [comment]
> Thanks for the help. I'm used to Debian and I'm just starting Arch so I'm just learning as I go.

this Edition is not completely ready ..
